### ISSUE TITLE
Trying to connect Myo with ESP32 Arduino

### ISSUE THREAD

**Issue by tho2gt** [vroland/MyoBridge#11]
Hi,

I'm trying to connect Myo with an ESP32 Arduino to read EMG data.

I tryed to use examples from the library, but they uses a serial port : 

`#include <MyoBridge.h>
#include <SoftwareSerial.h>

#define rxPin 2
#define txPin 3

//SoftwareSerial connexion à MyoBridge
SoftwareSerial bridgeSerial(rxPin, txPin);

//Initialise un objet MyoBridge
MyoBridge bridge(bridgeSerial);`

But ESP32 is not compatible with SoftwareSerial due to the BLE included on it.
I can't create a MyoBridge object without a SerialPort ?
Do you know how can I connect Myo with ESP32 ?

Sorry for my bad English 🥇

**Comment by vroland** [comment]
Hi Harinka,

Do you have any kind of serial UART communication available? Hardware and simulated (Softare-) ports will do. Maybe there is a similar library for ESP32?
If not, you cannot use this library as is.
Regards,
Valentin

**Comment by tho2gt** [comment]
Indeed, there is a specific library for ESP32, but I haven't been able to make it works with MyoBridge.

Maybe you can help me : [http://www.instructables.com/id/ESP32-BLE-Android-App-Arduino-IDE-AWESOME/](url)

I tried to follow this tutorial (I just skipped the app part) and change the program to make it work with MyoBridge. But it didn't work

**Comment by vroland** [comment]
I am sorry, but I do not think I can help you with this, as I have no experience with the ESP32 platform. But as this is about getting a serial port to work on the ESP, you could ask for help in a community more closely related to your platform :)
