### ISSUE TITLE
Myo+Arduino DUE

### ISSUE THREAD

**Issue by EPPS24** [vroland/MyoBridge#13]
Hello..
You could help me with a problem please ..
I need to connect myo with a arduino due .. but I have not been able to achieve it ...
what I have done is remove the serial software, and place it like this on this page, but the data is not sent, help with that please
https://www.codegists.com/code/arduino-hardware-serial/

**Comment by vroland** [comment]
Hey,
what exactly does "data is not sent" mean? Have you tried the original example with a software serial? What does you Myo do?

**Comment by EPPS24** [comment]
the with the arduino one and nano the signals emg and imu reciven correctly, but with the arduino due it stays in a connected status, but you do not see any data emg, the problem there is that in the arduino mega and due does not use the serial sofware uses serial1, serial2, so in the original code I change it to MyoBridge bridge (Serial1); 
and Serial1.begin (115200); 
but I do not know if that's right, that's why I need help, to communicate between the arduino mega or due and the bracelet, help please
