### ISSUE TITLE
My Myo doesn´t pair 

### ISSUE THREAD

**Issue by Eeddhem** [vroland/MyoBridge#14]
My Myo device doesn´t pair, I have the Module that is provided by DSD TECH and I already Upload de Firmware to it, but when I try to use the "printFirmwareInfo" example my Myo just doesn´t pair
This is de Module that I have 
![hm11](https://user-images.githubusercontent.com/39929630/45468061-65b79c80-b6e8-11e8-8e55-a25bd417ff6e.png)
And this happen in my serial monitor 
![sm](https://user-images.githubusercontent.com/39929630/45468107-9ac3ef00-b6e8-11e8-91ba-8fc84353ef9c.png)

**Comment by Eeddhem** [comment]
I will be very greatful if somebody can help me

**Comment by vroland** [comment]
As I do not own a Myo, I'm afraid I can't help you a lot with this. But there are a couple points you could check:
- Are you using the correct chip? This libary requires the CC2541 SoC.
- Is it properly flashed?
- Is the serial communication set up correctly?
- Is everything soldered well?
