### ISSUE TITLE
Compatibility with the new firmware for the Myo 1.5.1970

### ISSUE THREAD

**Issue by Eeddhem** [vroland/MyoBridge#15]
Do you know if this project is compatible with the new firmware for the arduino 1.5.1970?

**Comment by vroland** [comment]
As I said in previous comments, I do not own a Myo, unfortunately. I guess you have to try :/

**Comment by Eeddhem** [comment]
I have finally the example running whit the default Myo firmware, I guess I will try it but in a neat future. I'm gonna stay in touch to comment if it is possible, thank you for the attention.
